<?php

namespace Powon\Services\Implementation;

use Powon\Dao\MemberDAO;
use Powon\Dao\SessionDAO;
use Powon\Entity\Member;
use Powon\Entity\Session;
use Powon\Services\SessionService;
use Powon\Utils\Token;
use Psr\Log\LoggerInterface;

/**
 * Class SessionServiceImpl
 * The basic implementation of the session service
 * @package Powon\Services\Implementation
 */
class SessionServiceImpl implements SessionService
{

    /**
     * @var LoggerInterface
     */
    protected $log;

    /**
     * @var MemberDAO
     */
    protected $memberDAO;

    /**
     * @var SessionDAO
     */
    protected $sessionDAO;

    /**
     * The session entity corresponding with the current session
     * @var Session
     */
    private $session;

    /**
     * Logged in member.
     * @var Member
     */
    private $member;

    /**
     * Expiration in seconds.
     * @var int
     */
    private $expiration = 24*3600;

    /**
     * Default key for generating tokens.
     * @var string
     */
    private $key = 'xbP#uj$anK';
    
    /**
     * SessionServiceImpl constructor.
     * @param LoggerInterface $log
     * @param MemberDAO $memberDAO
     * @param SessionDAO $sessionDAO
     */
    public function __construct(LoggerInterface $log, MemberDAO $memberDAO, SessionDAO $sessionDAO)
    {
        $this->log = $log;
        $this->memberDAO = $memberDAO;
        $this->sessionDAO = $sessionDAO;
    }

    /**
     * Loads a session for the current request.
     * @param string $token An authentication token as generated by the @link \Powon\Utils\Token.
     * @return int (SESSION_ACTIVE, SESSION_EXPIRED, SESSION_DOES_NOT_EXIST)
     */
    public function loadSession($token)
    {
        $this->session = $this->sessionDAO->getSession($token);
        if ($this->session && time() >= ($this->session->getLastAccess() + $this->expiration)) {
            $this->log->info("Session with token expired.", array('token' => $token));
            $this->sessionDAO->deleteSession($token);
            $this->session = null;
            $this->member = null;
            return SessionService::SESSION_EXPIRED;
        } else if ($this->session) {
            // load member
            $member_id = $this->session->getMemberId();
            $this->log->debug('Loaded session for member with id.', array('token' => $token, 'member' => $member_id));
            $this->member = $this->memberDAO->getMemberById($member_id);
            // update session's last_access.
            $this->session->setLastAccess(time());
            $this->sessionDAO->updateSession($this->session);
            return SessionService::SESSION_ACTIVE;
        } else {
            return SessionService::SESSION_DOES_NOT_EXIST;
        }
    }

    /**
     * Called after authentication. It generates a new session for the given user.
     * @param int $member_id
     */
    private function generateSessionForMember() {
        assert($this->member != null);
        $member_id = $this->member->getMemberId();
        $data['token'] = Token::generate($this->key);
        $this->log->debug('Generated token for member.', array('member_id' => $member_id, 'token' => $data['token']));
        $data['session_data'] = array();
        $data['member_id'] = $member_id;
        $data['last_access'] = time();
        $this->session = new Session($data);
        $this->sessionDAO->createSession($this->session);
    }

    /**
     * Authenticates a user by username.
     * @param string $username
     * @param string $password
     * @return bool true on success, false otherwise
     */
    public function authenticateUserByUsername($username, $password)
    {
        $temp_member = $this->memberDAO->getMemberByUsername($username,true);
        if (!$temp_member) {
            $this->log->debug('Member not found.', array('username' => $username));
            $this->member = null;
            $this->session = null;
            return false;
        } else {
            $hashed_pwd = $temp_member->getHashedPassword();
            if (password_verify($password, $hashed_pwd)) {
                $this->member = $temp_member;
                $this->generateSessionForMember();
                return true;
            } else {
                $this->log->debug('Invalid password for member', array('username' => $username));
                return false;
            }
        }
    }

    /**
     * @param string $email
     * @param string $password
     * @return bool true on success, false otherwise
     */
    public function authenticateUserByEmail($email, $password)
    {
        $temp_member = $this->memberDAO->getMemberByEmail($email,true);
        if (!$temp_member) {
            $this->log->debug('Member not found.', array('email' => $email));
            $this->member = null;
            $this->session = null;
            return false;
        } else {
            $hashed_pwd = $temp_member->getHashedPassword();
            if (password_verify($password, $hashed_pwd)) {
                $this->member = $temp_member;
                $this->generateSessionForMember();
                return true;
            } else {
                $this->log->debug('Invalid password for member', array('email' => $email));
                $this->member = null;
                return false;
            }
        }
    }

    /**
     * Returns true if a user is authenticated.
     * @return bool
     */
    public function isAuthenticated()
    {
        return ($this->member != null && $this->session != null);
    }

    /**
     * Tells whether the currently authenticated member is an admin.
     * @return bool
     */
    public function isAdmin()
    {
        if ($this->member != null) {
            return $this->member->isAdmin();
        }
        return false;
    }

    /**
     * Gets the currently authenticated member
     * @return \Powon\Entity\Member|null
     */
    public function getAuthenticatedMember()
    {
        return $this->member;
    }

    /**
     * Saves the current session in the database
     * @return bool
     */
    public function saveSession()
    {
        if (!$this->session)
            return false;
        if ($this->sessionDAO->updateSession($this->session))
            return true;
        else
            return false;
    }

    /**
     * Gets the current Session entity.
     * @return \Powon\Entity\Session|null
     */
    public function getSession()
    {
        return $this->session;
    }

    /**
     * Destroys the current session (if any)
     * from the database.
     * @return bool True on success, false otherwise.
     */
    public function destroySession()
    {
        if ($this->session) {
            $token = $this->session->getToken();
            $this->log->debug('Deleting session with $token.', array('token'=>$token));
            $this->member = null;
            $this->session = null;
            return $this->sessionDAO->deleteSession($token);
        }
        return false;
    }

    /**
     * Destroys all sessions for the current user.
     * @return bool True on success, false otherwise.
     */
    public function destroyAllSessions()
    {
        if ($this->member) {
            $id = $this->member->getMemberId();
            $this->log->debug('Deleting all sessions for user id.', array('member_id' => $id));
            $this->session = null;
            $this->member = null;
            return $this->sessionDAO->deleteAllSessionsForMember($id);
        }
        return false;
    }

    /**
     * Sets the expiration time of the unused tokens.
     * Tokens not used after this time will become invalid or garbage collected.
     * @param int $seconds
     * @return void
     */
    public function setExpiration($seconds)
    {
        $this->expiration = $seconds;
    }

    /**
     * Eliminates expired sessions.
     */
    public function garbageCollect()
    {
        $latestValidTime = time() - $this->expiration;
        $this->sessionDAO->deleteSessionsWithLastAccessSmallerThan($latestValidTime);
    }

    /**
     * Sets a key to use when generating tokens.
     * @param string $newKey
     * @return void
     */
    public function setKey($newKey)
    {
        $this->key = $newKey;
    }
}